### ISSUE TITLE
Suggestion: new extension key

### ISSUE THREAD

**Issue by georgringer** [captcha-eu/typo3#4]
Hey!

I suggest to use a different extension key "captcha_eu". I registered it in the meantime just so that it is reserved.
Reasons:

- shorter
- no need to have the suffix "_typo3" because we are in the TYPO3 universe anyway
- I personally don't like the "captchaeu" with "aeu" ^^

**Comment by hjanuschka** [comment]
`aeu`  good catch. honestly - not brave enought todo the renaming stunt, not sure what customer's setup breaks
