### ISSUE TITLE
Locallang files not correct

### ISSUE THREAD

**Issue by Mon-Tea** [captcha-eu/typo3#9]
If I try to use the Siteconfiguration on a special site in TYPO3 11.5.35 with german backend I got an exception:

`The path provided does not point to an existing and accessible well-formed XML file. Reason: Entity 'uuml' not defined in /var/www/html/deployer/releases/787/public/typo3conf/ext/captchaeu_typo3/Resources/Private/Language/de.locallang.xlf, line 6`

Fix: The `&ouuml;` and `&uuml;` should be inside of CDATA, like this:
` <source><![CDATA[Captcha.eu L&ouml;sung ist ung&uuml;ltig]]></source>`

I think the the <target> tags are also missing.

**Comment by hjanuschka** [comment]
many thanks! your fix is totally correct!

v1.0.4 has been published.
https://github.com/captcha-eu/typo3/commit/644245a410fc3d744d2571e2f5a8d098e6198450

**Comment by Mon-Tea** [comment]
Sorry missed the quotes for `<target>` before tag…
The german translation should be in the target section and the source (eng) should be also in the german lang file.

**Comment by hjanuschka** [comment]
done with v1.0.6 - could be so kind and confirm/test?
